nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

# Enable zero-installs for faster setup
enableGlobalCache: true

# Use exact versions for dependencies
preferInteractive: false